---
- name: Collect logs
  include: collect.yml
  when: artcl_collect|bool

- name: Generate docs
  include: create-docs.yml
  when:
    - artcl_gen_docs|bool
    - not artcl_collect|bool

- name: Publish logs
  include: publish.yml
  when:
    - artcl_publish|bool
    - not artcl_collect|bool
